source 'http://rubygems.org'

# Provides basic authentication functionality for testing parts of your engine
gem 'spree_auth_devise', :github => 'spree/spree_auth_devise', :branch => '1-3-stable'
# gem 'spree_flexi_variants', :git=>'git@github.com:jsqu99/spree_flexi_variants.git', :branch => 'spree-1-3-stable'
group :assets do
  gem 'therubyracer', :platforms => :ruby
end

gemspec
